require('dotenv').config();
require('./config/database');

const BabyCategory = require('./models/babyCategory');
const BabyProduct = require('./models/babyProduct');

(async function() {
    await BabyCategory.deleteMany({});
    const BabyCategorys = await BabyCategory.create([
        {name: 'Pants', image: '/images/shirts.jpg', sortOrder: 10},
        {name: 'Shirts', image: '/images/shirts.jpg', sortOrder: 11},
        {name: 'Coors Sets', image: '/images/shirts.jpg', sortOrder: 12},
        {name: 'Pyjamas', image: '/images/shirts.jpg', sortOrder: 13},
        {name: 'Dresses', image: '/images/shirts.jpg', sortOrder: 14},
        {name: 'Sweaters', image: '/images/shirts.jpg', sortOrder: 15},
        {name: 'Swimwear', image: '/images/shirts.jpg', sortOrder: 16},
        {name: 'mclaren', image: '/images/shirts.jpg', sortOrder: 17},
        {name: 'mercedes', image: '/images/shirts.jpg', sortOrder: 18},
        {name: 'nissan', image: '/images/shirts.jpg', sortOrder: 19},
        {name: 'porsche', image: '/images/shirts.jpg', sortOrder: 20},
        {name: 'rolls-royce', image: '/images/shirts.jpg', sortOrder: 21},
    ]);
    
    let audi = BabyCategorys[0]
    let bentley = BabyCategorys[1]
    let bmw = BabyCategorys[2]
    let cadillac = BabyCategorys[3]
    let ferrari = BabyCategorys[4]
    let lamborghini = BabyCategorys[5]
    let landrover = BabyCategorys[6]
    let mclaren = BabyCategorys[7]
    let mercedes = BabyCategorys[8]
    let nissan = BabyCategorys[9]
    let porsche = BabyCategorys[10]
    let rolls = BabyCategorys[11]

    await BabyProduct.deleteMany({});
    const BabyProducts = await BabyProduct.create([
        // AUDI /////////////////
        {name: 'Audi A3 2022 White', 
        BabyCategory: audi, price: 200,
        size: ['Newborn', '0-3 months', '3-6 months'],
        image:[ '/images/audi/a32022white/1.webp',
        '/images/audi/a32022white/2.webp',
        '/images/audi/a32022white/3.webp',
        '/images/audi/a32022white/4.webp',
        '/images/audi/a32022white/5.webp',
    ], 
},
        {name: 'NEW! Audi RS Q8 (Grey)', 
        BabyCategory: audi, price: 200,
        size: ['Newborn', '0-3 months', '3-6 months'],
        image:[ '/images/audi/q32022/1.webp',
    ], 
},
        {name: 'AUDI A8L 2020 (BLACK)', 
        BabyCategory: audi, price: 200,
        size: ['Newborn', '0-3 months', '3-6 months'],
        image:[ '/images/audi/a8l2020black/1.webp',
        '/images/audi/a8l2020black/2.webp',
        '/images/audi/a8l2020black/3.webp',
        '/images/audi/a8l2020black/4.webp',
        '/images/audi/a8l2020black/5.webp',
        '/images/audi/a8l2020black/6.webp',
        '/images/audi/a8l2020black/7.webp',
    ], 
},
        {name: 'Audi Q5 2022', 
        BabyCategory: audi, price: 166,
        size: ['Newborn', '0-3 months', '3-6 months'],
        image:[ '/images/audi/q52022/1.webp',
    ], 
},
        {name: 'AUDI Q8 2022', 
        BabyCategory: audi, price: 192,
        size: ['Newborn', '0-3 months', '3-6 months'],
        image:[ '/images/audi/q82022/1.webp',
        '/images/audi/q82022/2.webp',
    ], 
},
        {name: 'AUDI R8 2021 (GREY NARDO)', 
        BabyCategory: audi, price: 200,
        size: ['Newborn', '0-3 months', '3-6 months'],
        image:[ '/images/audi/r82021greynardo/1.webp',
        '/images/audi/r82021greynardo/2.webp',
        '/images/audi/r82021greynardo/3.webp',
        '/images/audi/r82021greynardo/4.webp',
        '/images/audi/r82021greynardo/5.jpg',
        '/images/audi/r82021greynardo/6.webp',
        '/images/audi/r82021greynardo/7.webp',
        '/images/audi/r82021greynardo/8.webp',
        '/images/audi/r82021greynardo/9.webp',
    ], 
},
        {name: 'AUDI R8 2021 (WHITE)', 
        BabyCategory: audi, price: 200,
        size: ['Newborn', '0-3 months', '3-6 months'],
        image:[ '/images/audi/r82021white/1.webp',
        '/images/audi/r82021white/2.webp',
        '/images/audi/r82021white/3.webp',
        '/images/audi/r82021white/4.webp',
        '/images/audi/r82021white/5.webp',
        '/images/audi/r82021white/6.webp',
        '/images/audi/r82021white/7.webp',
        '/images/audi/r82021white/8.webp',
        '/images/audi/r82021white/9.webp',
        '/images/audi/r82021white/10.webp',
    ], 
},
        {name: 'Audi RS5 Black', 
        BabyCategory: audi, price: 230,
        size: ['Newborn', '0-3 months', '3-6 months'],
        image:[ '/images/audi/rs5black/1.webp',
        '/images/audi/rs5black/2.webp',
        '/images/audi/rs5black/3.webp',
        '/images/audi/rs5black/4.webp',
        '/images/audi/rs5black/5.webp',
        '/images/audi/rs5black/6.webp',
        '/images/audi/rs5black/7.webp',
        '/images/audi/rs5black/8.webp',
    ], 
},
        {name: 'Audi RS5 Green 2022', 
        BabyCategory: audi, price: 282,
        size: ['Newborn', '0-3 months', '3-6 months'],
        image:[ '/images/audi/rs5green2022/1.webp',
        '/images/audi/rs5green2022/2.webp',
        '/images/audi/rs5green2022/3.webp',
        '/images/audi/rs5green2022/4.webp',
        '/images/audi/rs5green2022/5.webp',
        '/images/audi/rs5green2022/6.webp',
        '/images/audi/rs5green2022/7.webp',
        '/images/audi/rs5green2022/8.webp',
        '/images/audi/rs5green2022/9.webp',
    ], 
},
        {name: 'Audi RS Q8 (Black)', 
        BabyCategory: audi, price: 256,
        size: ['Newborn', '0-3 months', '3-6 months'],
        image:[ '/images/audi/rs8black/1.webp',
        '/images/audi/rs8black/2.webp',
        '/images/audi/rs8black/3.webp',
        '/images/audi/rs8black/4.webp',
        '/images/audi/rs8black/5.webp',
        '/images/audi/rs8black/6.webp',
        '/images/audi/rs8black/7.webp',
        '/images/audi/rs8black/8.webp',
    ], 
},
        {name: 'NEW! Audi RS Q8 (Grey)', 
        BabyCategory: audi, price: 200,
        size: ['Newborn', '0-3 months', '3-6 months'],
        image:[ '/images/audi/rs8grey/1.webp',
        '/images/audi/rs8grey/2.webp',
        '/images/audi/rs8grey/3.webp',
        '/images/audi/rs8grey/4.webp',
        '/images/audi/rs8grey/5.webp',
        '/images/audi/rs8grey/6.webp',
        '/images/audi/rs8grey/7.webp',
    ], 
},
        {name: 'AUDI RS6 2023 (NARDO GREY)', 
        BabyCategory: audi, price: 200,
        size: ['Newborn', '0-3 months', '3-6 months'],
        image:[ '/images/audi/rs62023nardogrey/1.webp',
        '/images/audi/rs62023nardogrey/2.webp',
        '/images/audi/rs62023nardogrey/3.webp',
        '/images/audi/rs62023nardogrey/4.webp',
        '/images/audi/rs62023nardogrey/5.webp',
    ], 
},
        {name: 'Audi RS7 2021 (Nardo Grey)', 
        BabyCategory: audi, price: 200,
        size: ['Newborn', '0-3 months', '3-6 months'],
        image:[ '/images/audi/rs72021nardogrey/1.jpeg',
        '/images/audi/rs72021nardogrey/2.webp',
        '/images/audi/rs72021nardogrey/3.webp',
        '/images/audi/rs72021nardogrey/4.webp',
    ], 
},
        {name: 'Audi RS Q8 (White)', 
        BabyCategory: audi, price: 200,
        size: ['Newborn', '0-3 months', '3-6 months'],
        image:[ '/images/audi/rsq8white/1.jpeg',
        '/images/audi/rsq8white/2.webp',
        '/images/audi/rsq8white/3.webp',
        '/images/audi/rsq8white/4.webp',
    ], 
},
        {name: 'Audi RS Q3 2022', 
        BabyCategory: audi, price: 200,
        size: ['Newborn', '0-3 months', '3-6 months'],
        image:[ '/images/audi/rsq32022/1.webp',
    ], 
},
        {name: 'AUDI A6 2022 (BLACK)', 
        BabyCategory: audi, price: 103,
        size: ['Newborn', '0-3 months', '3-6 months'],
        image:[ '/images/audi/a62022black/1.jpeg',
                '/images/audi/a62022black/2.webp',
                '/images/audi/a62022black/3.webp',
                '/images/audi/a62022black/4.webp',
                '/images/audi/a62022black/5.webp',
                '/images/audi/a62022black/6.webp',
    ], 
},
//        MCLAREN /////////////////
        {name: 'McLaren 570S 2020 (GREEN)', 
        BabyCategory: mclaren, price: 844,
        size: ['Newborn', '0-3 months', '3-6 months'],
        image:[ '/images/mclaren/5702020/1.webp',
                
    ], 
},
        {name: 'McLaren 720S 2020 (WHITE)', 
        BabyCategory: mclaren, price: 844,
        size: ['Newborn', '0-3 months', '3-6 months'],
        image:[ '/images/mclaren/7202020/1.webp',
                '/images/mclaren/7202020/2.webp',
                '/images/mclaren/7202020/3.webp',
                
    ], 
},
//      FEWRRARI /////////////////
        {name: 'FERRARI 488 GTB 2022 (RED)', 
        BabyCategory: ferrari, price: 629,
        size: ['Newborn', '0-3 months', '3-6 months'],
        image:[ '/images/ferrari/488gtb/1.webp',
                '/images/ferrari/488gtb/2.webp',
                '/images/ferrari/488gtb/3.webp',
                '/images/ferrari/488gtb/4.webp',
                '/images/ferrari/488gtb/5.webp',
                '/images/ferrari/488gtb/6.webp',
                '/images/ferrari/488gtb/7.webp',
                '/images/ferrari/488gtb/8.webp',
                '/images/ferrari/488gtb/9.webp',
                '/images/ferrari/488gtb/10.webp',     
    ], 
},
        {name: 'Ferrari 488 Spider', 
        BabyCategory: ferrari, price: 629,
        image:[ '/images/ferrari/488spider/1.webp',
                '/images/ferrari/488spider/2.webp',
                '/images/ferrari/488spider/3.webp',   
    ], 
},
        {name: 'Ferrari F8 Spider 2022', 
        BabyCategory: ferrari, price: 629,
        size: ['Newborn', '0-3 months', '3-6 months'],
        image:[ '/images/ferrari/f8spider/1.webp',
                '/images/ferrari/f8spider/2.webp',
                '/images/ferrari/f8spider/3.webp',
                '/images/ferrari/f8spider/4.webp',
                '/images/ferrari/f8spider/5.webp',
                '/images/ferrari/f8spider/6.webp',
                '/images/ferrari/f8spider/7.webp',
                '/images/ferrari/f8spider/8.webp',
                '/images/ferrari/f8spider/9.webp',                
    ], 
},
        {name: 'Ferrari Portofino', 
        BabyCategory: ferrari, price: 461,
        size: ['Newborn', '0-3 months', '3-6 months'],
        image:[ '/images/ferrari/portofino/1.webp',
                '/images/ferrari/portofino/2.webp',
                '/images/ferrari/portofino/3.webp',
                '/images/ferrari/portofino/4.webp',
                '/images/ferrari/portofino/5.webp',
                '/images/ferrari/portofino/6.webp',
                '/images/ferrari/portofino/7.webp',
                '/images/ferrari/portofino/8.webp',
                '/images/ferrari/portofino/9.webp',
                '/images/ferrari/portofino/10.webp',
                '/images/ferrari/portofino/11.webp',
                
    ], 
},
//      BENTLEY /////////////////
        {name: 'BENTLEY BENTAYGA 2020', 
        BabyCategory: bentley, price: 1221,
        size: ['Newborn', '0-3 months', '3-6 months'],
        image:[ '/images/bentley/bentayaga2020/1.webp',
                '/images/bentley/bentayaga2020/2.webp',
                '/images/bentley/bentayaga2020/3.webp',
                '/images/bentley/bentayaga2020/4.webp',
                '/images/bentley/bentayaga2020/5.webp',

    ], 
},
        {name: 'BENTLEY BENTAYGA 2021 (BLACK)', 
        BabyCategory: bentley, price: 1716,
        size: ['Newborn', '0-3 months', '3-6 months'],
        image:[ '/images/bentley/bentayaga2021black/1.webp',
                '/images/bentley/bentayaga2021black/2.webp',
                '/images/bentley/bentayaga2021black/3.webp',
                '/images/bentley/bentayaga2021black/4.webp',
    ], 
},
        {name: 'BENTLEY BENTAYGA 2021 (BLUE)', 
        BabyCategory: bentley, price: 1461,
        size: ['Newborn', '0-3 months', '3-6 months'],
        image:[ '/images/bentley/bentayaga2021blue/1.webp',
                '/images/bentley/bentayaga2021blue/2.webp',
                '/images/bentley/bentayaga2021blue/3.webp',
                '/images/bentley/bentayaga2021blue/4.webp',
                '/images/bentley/bentayaga2021blue/5.webp',
                '/images/bentley/bentayaga2021blue/6.webp',
                '/images/bentley/bentayaga2021blue/7.webp',
                '/images/bentley/bentayaga2021blue/8.webp',
                '/images/bentley/bentayaga2021blue/9.webp',
                '/images/bentley/bentayaga2021blue/11.webp',
                '/images/bentley/bentayaga2021blue/12.webp',
                
    ], 
},
        {name: 'Bentley Continental GT Convertible (GREY)', 
        BabyCategory: bentley, price: 2299,
        size: ['Newborn', '0-3 months', '3-6 months'],
        image:[ '/images/bentley/continentalgt/1.webp',
                '/images/bentley/continentalgt/2.webp',
                '/images/bentley/continentalgt/3.webp',
                '/images/bentley/continentalgt/4.webp',
                '/images/bentley/continentalgt/5.webp',
                
    ], 
},
        {name: 'BENTLEY GT 2021 (GREY)', 
        BabyCategory: bentley, price: 639,
        size: ['Newborn', '0-3 months', '3-6 months'],
        image:[ '/images/bentley/gt2021grey/1.webp',
                '/images/bentley/gt2021grey/2.webp',
                '/images/bentley/gt2021grey/3.webp',
                '/images/bentley/gt2021grey/4.webp',
                '/images/bentley/gt2021grey/5.webp',
                
    ], 
},
        {name: 'BENTLEY GT 2022 FIRST EDITION (WHITE)', 
        BabyCategory: bentley, price: 461,
        size: ['Newborn', '0-3 months', '3-6 months'],
        image:[ '/images/bentley/gt2022/1.webp',
                '/images/bentley/gt2022/2.webp',
                '/images/bentley/gt2022/3.webp',
                '/images/bentley/gt2022/4.webp',
                '/images/bentley/gt2022/5.webp',            
    ], 
},
        {name: 'BENTLEY GTC ( White )', 
        BabyCategory: bentley, price: 639,
        size: ['Newborn', '0-3 months', '3-6 months'],
        image:[ '/images/bentley/gtcwhite/1.webp',
                '/images/bentley/gtcwhite/2.webp',
                '/images/bentley/gtcwhite/3.webp',
                '/images/bentley/gtcwhite/4.webp',
                '/images/bentley/gtcwhite/5.webp',
                '/images/bentley/gtcwhite/6.webp',             
    ], 
},
//     BMW /////////////////
        {name: 'BMW 750Li 2020 (BLACK)', 
        BabyCategory: bmw, price: 258,
        size: ['Newborn', '0-3 months', '3-6 months'],
        image:[ '/images/bmw/bmw750li/1.webp',
                '/images/bmw/bmw750li/2.webp',
                '/images/bmw/bmw750li/3.webp',
                '/images/bmw/bmw750li/4.webp',
                '/images/bmw/bmw750li/5.webp',
                '/images/bmw/bmw750li/6.webp',             
                '/images/bmw/bmw750li/7.webp',             
    ], 
},
        {name: 'BMW COMPETITION 2022 (GREEN)', 
        BabyCategory: bmw, price: 258,
        size: ['Newborn', '0-3 months', '3-6 months'],
        image:[ '/images/bmw/bmw2022green/1.webp',
                '/images/bmw/bmw2022green/2.webp',
                '/images/bmw/bmw2022green/3.webp',
                '/images/bmw/bmw2022green/4.webp',
                '/images/bmw/bmw2022green/5.webp',         
    ], 
},
        {name: 'BMW COMPETITION 2023 (LEMON)', 
        BabyCategory: bmw, price: 238,
        size: ['Newborn', '0-3 months', '3-6 months'],
        image:[ '/images/bmw/bmw2023lemon/1.webp',
                '/images/bmw/bmw2023lemon/2.webp',
                '/images/bmw/bmw2023lemon/3.webp',
                '/images/bmw/bmw2023lemon/4.webp',
                '/images/bmw/bmw2023lemon/5.webp',
                '/images/bmw/bmw2023lemon/6.webp',             
                '/images/bmw/bmw2023lemon/7.webp',             
                '/images/bmw/bmw2023lemon/8.webp',             
                '/images/bmw/bmw2023lemon/9.webp',             
                '/images/bmw/bmw2023lemon/10.webp',             
                '/images/bmw/bmw2023lemon/11.webp',             
                '/images/bmw/bmw2023lemon/12.webp',             
                '/images/bmw/bmw2023lemon/13.webp',             
                '/images/bmw/bmw2023lemon/14.webp',             
    ], 
},
        {name: 'BMW X6 ( Black )', 
        BabyCategory: bmw, price: 103,
        size: ['Newborn', '0-3 months', '3-6 months'],
        image:[ '/images/bmw/bmwx6/1.avif.avif',
                '/images/bmw/bmwx6/2.webp',
                '/images/bmw/bmwx6/3.webp',
                '/images/bmw/bmwx6/4.webp',            
    ], 
},
    //    cadillac /////////////////
        {name: 'Cadillac Escalade XL ( Black )', 
                BabyCategory: cadillac, price: 193,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/cadilac/cadblackxl/1.webp',
                        '/images/cadilac/cadblackxl/2.webp',
                        '/images/cadilac/cadblackxl/3.webp',
                        '/images/cadilac/cadblackxl/4.webp',           
            ], 
        },
        {name: 'Cadillac Escalade ( Black )', 
                BabyCategory: cadillac, price: 238,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/cadilac/cadblack/1.webp',
                        '/images/cadilac/cadblack/2.webp',
                        '/images/cadilac/cadblack/3.webp',
                        '/images/cadilac/cadblack/4.webp',
                        '/images/cadilac/cadblack/5.webp',
                        '/images/cadilac/cadblack/6.webp',             
                        '/images/cadilac/cadblack/7.webp',             
                        '/images/cadilac/cadblack/8.webp',             
                        '/images/cadilac/cadblack/9.webp',             
                        '/images/cadilac/cadblack/10.webp',             
                        '/images/cadilac/cadblack/11.webp',             
                        '/images/cadilac/cadblack/12.webp',             
                        '/images/cadilac/cadblack/13.webp',             
            ], 
        },
        //  nissan /////////////////
        {name: 'NISSAN PATROL 2022 (BLACK)', 
                BabyCategory: nissan, price: 155,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/nissan/nissan2022black/1.webp',
                        '/images/nissan/nissan2022black/2.webp',
                        '/images/nissan/nissan2022black/3.webp',
                        '/images/nissan/nissan2022black/4.webp',           
            ], 
        },
        {name: 'NISSAN PATROL 2022 (WHITE)', 
                BabyCategory: nissan, price: 155,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/nissan/nissan2022white/1.webp',
                        '/images/nissan/nissan2022white/2.webp',
                        '/images/nissan/nissan2022white/3.webp',
                        '/images/nissan/nissan2022white/4.webp',           
                        '/images/nissan/nissan2022white/5.webp',
                        '/images/nissan/nissan2022white/6.webp',
                        '/images/nissan/nissan2022white/7.webp',           
                        '/images/nissan/nissan2022white/8.webp',
                        '/images/nissan/nissan2022white/9.webp',
                        '/images/nissan/nissan2022white/10.webp',           
                        '/images/nissan/nissan2022white/11.webp',
                        '/images/nissan/nissan2022white/12.webp',
                        '/images/nissan/nissan2022white/13.webp',           
                        '/images/nissan/nissan2022white/14.webp',           
            ], 
        },
        {name: 'NISSAN GT-R (BLACK)', 
                BabyCategory: nissan, price: 593,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/nissan/nissangtrblack/1.webp',
                        '/images/nissan/nissangtrblack/2.webp',
                        '/images/nissan/nissangtrblack/3.webp',
                        '/images/nissan/nissangtrblack/4.webp',           
            ], 
        },
        // porche /////////////////
        {name: 'Porsche 911 Carrera Convertible (BLACK)', 
                BabyCategory: porsche, price: 387,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/porsche/p911carrera/1.webp',
                        '/images/porsche/p911carrera/2.webp',
                        '/images/porsche/p911carrera/3.webp',
                        '/images/porsche/p911carrera/4.webp',           
                        '/images/porsche/p911carrera/5.webp',           
                        '/images/porsche/p911carrera/6.webp',           
                        '/images/porsche/p911carrera/7.webp',           
            ], 
        },
        {name: 'Porsche 911 TURBO4S', 
                BabyCategory: porsche, price: 644,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/porsche/p911turbo4s/1.webp',
                        '/images/porsche/p911turbo4s/2.webp',
                        '/images/porsche/p911turbo4s/3.webp',
                        '/images/porsche/p911turbo4s/4.webp',           
                        '/images/porsche/p911turbo4s/5.webp',           
                        '/images/porsche/p911turbo4s/6.webp',           
                        '/images/porsche/p911turbo4s/7.webp',           
                        '/images/porsche/p911turbo4s/8.webp',
                        '/images/porsche/p911turbo4s/9.webp',
                        '/images/porsche/p911turbo4s/10.webp',           
                        '/images/porsche/p911turbo4s/11.webp',           
                        '/images/porsche/p911turbo4s/12.webp',           
            ], 
        },
        {name: 'Porche 911 Turbo S (BLACK)', 
                BabyCategory: porsche, price: 367,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/porsche/p911turbosblack/1.webp',
                        '/images/porsche/p911turbosblack/2.webp',
                        '/images/porsche/p911turbosblack/3.webp',
                        '/images/porsche/p911turbosblack/4.webp',                   
            ], 
        },
        {name: 'PORSCHE CAYENNE 2022 (BLACK)', 
                BabyCategory: porsche, price: 206,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/porsche/pcayenne2022black/1.webp',
                        '/images/porsche/pcayenne2022black/2.webp',
                        '/images/porsche/pcayenne2022black/3.webp',
                        '/images/porsche/pcayenne2022black/4.webp',           
                        '/images/porsche/pcayenne2022black/5.webp',           
                        '/images/porsche/pcayenne2022black/6.webp',           
                        '/images/porsche/pcayenne2022black/7.webp',           
            ], 
        },
        {name: 'Porsche Macan Black', 
                BabyCategory: porsche, price: 181,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/porsche/pmacanblack/1.webp',
                        '/images/porsche/pmacanblack/2.webp',
                        '/images/porsche/pmacanblack/3.webp',
                        '/images/porsche/pmacanblack/4.webp',           
                        '/images/porsche/pmacanblack/5.webp',           
                        '/images/porsche/pmacanblack/6.webp',           
                        '/images/porsche/pmacanblack/7.webp',           
                        '/images/porsche/pmacanblack/8.webp',           
                        '/images/porsche/pmacanblack/9.webp',           
            ], 
        },
        {name: 'Porsche Macan Gray', 
                BabyCategory: porsche, price: 155,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/porsche/pmacangray/1.webp',
                        '/images/porsche/pmacangray/2.webp',
                        '/images/porsche/pmacangray/3.webp',
                        '/images/porsche/pmacangray/4.webp',           
                        '/images/porsche/pmacangray/5.webp',           
                        '/images/porsche/pmacangray/6.webp',           
                        '/images/porsche/pmacangray/7.webp',           
            ], 
        },
        {name: 'Porche 911 Turbo S (WHITE)', 
                BabyCategory: porsche, price: 309,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/porsche/porsche911turbowhite/1.webp',
                        '/images/porsche/porsche911turbowhite/2.webp',
                        '/images/porsche/porsche911turbowhite/3.webp',
                        '/images/porsche/porsche911turbowhite/4.webp',           
                        '/images/porsche/porsche911turbowhite/5.webp',           
                        '/images/porsche/porsche911turbowhite/6.webp',           
                        '/images/porsche/porsche911turbowhite/7.webp',           
                        '/images/porsche/porsche911turbowhite/8.webp',           
                        '/images/porsche/porsche911turbowhite/9.webp',           
                        '/images/porsche/porsche911turbowhite/10.webp',           
                        '/images/porsche/porsche911turbowhite/11.webp',           
            ], 
        },
        {name: 'Porsche Panamera', 
                BabyCategory: porsche, price: 309,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/porsche/ppanamera/1.webp',
                        '/images/porsche/ppanamera/2.webp',
                        '/images/porsche/ppanamera/3.webp',
                        '/images/porsche/ppanamera/4.webp',           
                        '/images/porsche/ppanamera/5.webp',           
                        '/images/porsche/ppanamera/6.webp',           
            ], 
        },
        // rolls /////////////////
        {name: 'ROLLS ROYCE CULLINAN 2022 (WHITE)', 
                BabyCategory: rolls, price: 773,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/rolls-royce/rrcullinan2022/1.webp',
                        '/images/rolls-royce/rrcullinan2022/2.webp',
                        '/images/rolls-royce/rrcullinan2022/3.webp',
                        '/images/rolls-royce/rrcullinan2022/4.webp',           
                        '/images/rolls-royce/rrcullinan2022/5.webp',           
                        '/images/rolls-royce/rrcullinan2022/6.webp',           
            ], 
        },
        {name: 'ROLLS ROYCE CULLINAN 2022 (GREEN)', 
                BabyCategory: rolls, price: 902,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/rolls-royce/rrcullinan2022green/1.webp',
                        '/images/rolls-royce/rrcullinan2022green/2.webp',
                        '/images/rolls-royce/rrcullinan2022green/3.webp',
                        '/images/rolls-royce/rrcullinan2022green/4.webp',           
                        '/images/rolls-royce/rrcullinan2022green/5.webp',           
                        '/images/rolls-royce/rrcullinan2022green/6.webp',           
            ], 
        },
        {name: 'ROLLS ROYCE CULLINAN 2022 (GREY NARDO)', 
                BabyCategory: rolls, price: 902,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/rolls-royce/rrcullinan2022greynardo/1.webp',
                        '/images/rolls-royce/rrcullinan2022greynardo/2.webp',
                        '/images/rolls-royce/rrcullinan2022greynardo/3.webp',
                        '/images/rolls-royce/rrcullinan2022greynardo/4.webp',           
                        '/images/rolls-royce/rrcullinan2022greynardo/5.webp',           
                        '/images/rolls-royce/rrcullinan2022greynardo/6.webp',           
            ], 
        },
        {name: 'ROLLS ROYCE CULLINAN 2022 (WHITE)', 
                BabyCategory: rolls, price: 773,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/rolls-royce/rrcullinan2022white/1.webp',
                        '/images/rolls-royce/rrcullinan2022white/2.webp',
                        '/images/rolls-royce/rrcullinan2022white/3.webp',
                        '/images/rolls-royce/rrcullinan2022white/4.webp',           
                        '/images/rolls-royce/rrcullinan2022white/5.webp',           
            ], 
        },
        {name: 'ROLLS ROYCE CULLINAN BLACK BADGE 2022 (BLACK)', 
                BabyCategory: rolls, price: 902,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/rolls-royce/rrcullinanblackbadge2022/1.webp',
                        '/images/rolls-royce/rrcullinanblackbadge2022/2.webp',
                        '/images/rolls-royce/rrcullinanblackbadge2022/3.webp',
                        '/images/rolls-royce/rrcullinanblackbadge2022/4.webp',           
                        '/images/rolls-royce/rrcullinanblackbadge2022/5.webp',           
                        '/images/rolls-royce/rrcullinanblackbadge2022/6.webp',           
                        '/images/rolls-royce/rrcullinanblackbadge2022/7.webp',           
            ], 
        },
        {name: 'ROLLS ROYCE DAWN 2020 (BLACK)', 
                BabyCategory: rolls, price: 747,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/rolls-royce/rrdawn2020black/1.webp',
                        '/images/rolls-royce/rrdawn2020black/2.webp',
                        '/images/rolls-royce/rrdawn2020black/3.webp',
                        '/images/rolls-royce/rrdawn2020black/4.webp',           
                        '/images/rolls-royce/rrdawn2020black/5.webp',           
                        '/images/rolls-royce/rrdawn2020black/6.webp',           
            ], 
        },
        {name: 'ROLLS ROYCE GHOST 2020 (SILVER)', 
                BabyCategory: rolls, price: 490,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/rolls-royce/rrghost2020silver/1.webp',
                        '/images/rolls-royce/rrghost2020silver/2.webp',
                        '/images/rolls-royce/rrghost2020silver/3.webp',
                        '/images/rolls-royce/rrghost2020silver/4.webp',           
                        '/images/rolls-royce/rrghost2020silver/5.webp',           
            ], 
        },
        {name: 'ROLLS ROYCE WRAITH (BLACK)', 
                BabyCategory: rolls, price: 516,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/rolls-royce/rrwraitblack/1.webp',
                        '/images/rolls-royce/rrwraitblack/2.webp',
                        '/images/rolls-royce/rrwraitblack/3.webp',
                        '/images/rolls-royce/rrwraitblack/4.webp',           
                        '/images/rolls-royce/rrwraitblack/5.webp',           
                        '/images/rolls-royce/rrwraitblack/6.webp',           
            ], 
        },
        {name: 'ROLLS ROYCE WRAITH (BLUE)', 
                BabyCategory: rolls, price: 773,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/rolls-royce/rrwraitblue/1.webp',
                        '/images/rolls-royce/rrwraitblue/2.webp',
                        '/images/rolls-royce/rrwraitblue/3.webp',
                        '/images/rolls-royce/rrwraitblue/4.webp',           
                        '/images/rolls-royce/rrwraitblue/5.webp',           
                        '/images/rolls-royce/rrwraitblue/6.webp',           
                        '/images/rolls-royce/rrwraitblue/7.webp',
                        '/images/rolls-royce/rrwraitblue/8.webp',
                        '/images/rolls-royce/rrwraitblue/9.webp',           
                        '/images/rolls-royce/rrwraitblue/10.webp',           
                        '/images/rolls-royce/rrwraitblue/11.webp',           
                        '/images/rolls-royce/rrwraitblue/12.webp',
                        '/images/rolls-royce/rrwraitblue/13.webp',
                        '/images/rolls-royce/rrwraitblue/14.webp',           
                        '/images/rolls-royce/rrwraitblue/15.webp',           
                        '/images/rolls-royce/rrwraitblue/16.webp',           
            ], 
        },
        {name: 'ROLLS ROYCE WRAITH 2021 (NARDO GREY)', 
                BabyCategory: rolls, price: 593,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/rolls-royce/rrwraith2021/1.webp',
                        '/images/rolls-royce/rrwraith2021/2.webp',
                        '/images/rolls-royce/rrwraith2021/3.webp',
                        '/images/rolls-royce/rrwraith2021/4.webp',           
                        '/images/rolls-royce/rrwraith2021/5.webp',           
                        '/images/rolls-royce/rrwraith2021/6.webp',           
            ], 
        },
        {name: 'ROLLS ROYCE WRAITH (BLACK & BROWN)', 
                BabyCategory: rolls, price: 644,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/rolls-royce/rrwraithblackandbrown/1.jpeg',
                        '/images/rolls-royce/rrwraithblackandbrown/2.jpeg',
                        '/images/rolls-royce/rrwraithblackandbrown/3.webp',          
            ], 
        },
        // Land Rover /////////////////
        {name: 'Land Rover Defender 2022', 
                BabyCategory: landrover, price: 232,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/landrover/landroverdefender2022/1.webp',
                        '/images/landrover/landroverdefender2022/2.webp',
                        '/images/landrover/landroverdefender2022/3.webp',          
                        '/images/landrover/landroverdefender2022/4.webp',
                        '/images/landrover/landroverdefender2022/5.webp',          
                        '/images/landrover/landroverdefender2022/6.webp',
                        '/images/landrover/landroverdefender2022/7.webp',          
                        '/images/landrover/landroverdefender2022/8.webp',
                        '/images/landrover/landroverdefender2022/9.webp',          
            ], 
        },
        {name: 'RANGE ROVER SVR 2021 (WHITE)', 
                BabyCategory: landrover, price: 232,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/landrover/rangesvr2021/1.webp',
                        '/images/landrover/rangesvr2021/2.webp',
                        '/images/landrover/rangesvr2021/3.webp',          
                        '/images/landrover/rangesvr2021/4.webp',
                        '/images/landrover/rangesvr2021/5.webp',          
                        '/images/landrover/rangesvr2021/6.webp',          
            ], 
        },
        {name: 'Range Rover SVR ( Blue )', 
                BabyCategory: landrover, price: 232,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/landrover/rangesvrblue/1.webp',
                        '/images/landrover/rangesvrblue/2.webp',
                        '/images/landrover/rangesvrblue/3.webp',          
                        '/images/landrover/rangesvrblue/4.webp',
                        '/images/landrover/rangesvrblue/5.webp',          
                        '/images/landrover/rangesvrblue/6.webp',
                        '/images/landrover/rangesvrblue/7.webp',          
                        '/images/landrover/rangesvrblue/8.webp',
            ], 
        },
        {name: 'RANGE ROVER AUTOBIOGRAPHY 2020 (BLACK)', 
                BabyCategory: landrover, price: 899,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/landrover/rangeroverautobio/1.webp',
                        '/images/landrover/rangeroverautobio/2.webp',
                        '/images/landrover/rangeroverautobio/3.webp',          
                        '/images/landrover/rangeroverautobio/4.webp',
            ], 
        },
        {name: 'Range Rover HSE ( Black )', 
                BabyCategory: landrover, price: 699,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/landrover/rangeroverhseblack/1.webp',
                        '/images/landrover/rangeroverhseblack/2.webp',
                        '/images/landrover/rangeroverhseblack/3.webp',          
            ], 
        },
        {name: 'RANGE ROVER SPORT 2021 (WHITE)', 
                BabyCategory: landrover, price: 999,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/landrover/rangeroversport2021white/1.webp',
                        '/images/landrover/rangeroversport2021white/2.webp',
                        '/images/landrover/rangeroversport2021white/3.webp',          
                        '/images/landrover/rangeroversport2021white/4.webp',
                        '/images/landrover/rangeroversport2021white/5.webp',          
                        '/images/landrover/rangeroversport2021white/6.webp',
                        '/images/landrover/rangeroversport2021white/7.webp',          
                        '/images/landrover/rangeroversport2021white/8.webp',
            ], 
        },
        {name: 'Range Rover Sport V8 HSE 2022 ( Black )', 
                BabyCategory: landrover, price: 2249,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/landrover/rangeroversportv82022black/1.webp',
                        '/images/landrover/rangeroversportv82022black/2.webp',
                        '/images/landrover/rangeroversportv82022black/3.webp',          
                        '/images/landrover/rangeroversportv82022black/4.webp',
                        '/images/landrover/rangeroversportv82022black/5.webp',          
            ], 
        },
        {name: 'Range Rover SVR ( Orange )', 
                BabyCategory: landrover, price: 999,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/landrover/rangeroversvr0range/1.avif.avif',
                        '/images/landrover/rangeroversvr0range/2.webp',
                        '/images/landrover/rangeroversvr0range/3.webp',          
                        '/images/landrover/rangeroversvr0range/4.webp',

            ], 
        },
        {name: 'RANGE ROVER VELAR 2020 (BLACK)', 
                BabyCategory: landrover, price: 749,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/landrover/rangerovervelar2020black/1.webp',
                        '/images/landrover/rangerovervelar2020black/2.webp',
                        '/images/landrover/rangerovervelar2020black/3.webp',          
                        '/images/landrover/rangerovervelar2020black/4.webp',
            ], 
        },
        {name: 'RANGE ROVER VOGUE 2020 (BLACK)', 
                BabyCategory: landrover, price: 799,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/landrover/rangerovervogue2020black/1.webp',
                        '/images/landrover/rangerovervogue2020black/2.webp',
                        '/images/landrover/rangerovervogue2020black/3.webp',          
                        '/images/landrover/rangerovervogue2020black/4.webp',
                        '/images/landrover/rangerovervogue2020black/5.webp',          
                        '/images/landrover/rangerovervogue2020black/6.webp',
            ], 
        },
        //  Lamborghini /////////////////
        {name: 'LAMBORGHINI AVENTADOR 2022 (YELLOW)', 
                BabyCategory: lamborghini, price: 1160,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/lamborghini/laventador2022yellow/1.webp',
                        '/images/lamborghini/laventador2022yellow/2.webp',
                        '/images/lamborghini/laventador2022yellow/3.webp',          
                        '/images/lamborghini/laventador2022yellow/4.webp',
                        '/images/lamborghini/laventador2022yellow/5.webp',          
                        '/images/lamborghini/laventador2022yellow/6.webp',
                        '/images/lamborghini/laventador2022yellow/7.webp',          
            ], 
        },
        {name: 'LAMBORGHINI URUS 2022 (ORANGE)', 
                BabyCategory: lamborghini, price: 644,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/lamborghini/lurus2022orange/1.webp',
                        '/images/lamborghini/lurus2022orange/2.webp',
                        '/images/lamborghini/lurus2022orange/3.webp',          
                        '/images/lamborghini/lurus2022orange/4.webp',
                        '/images/lamborghini/lurus2022orange/5.webp',          
                        '/images/lamborghini/lurus2022orange/6.webp',
                        '/images/lamborghini/lurus2022orange/7.webp',          
                        '/images/lamborghini/lurus2022orange/8.webp',          
                        '/images/lamborghini/lurus2022orange/9.webp',          
                        '/images/lamborghini/lurus2022orange/10.webp',          
                        '/images/lamborghini/lurus2022orange/11.webp',          
                        '/images/lamborghini/lurus2022orange/12.webp',          
            ], 
        },
        {name: 'LAMBORGHINI URUS 2023 (GREEN)', 
                BabyCategory: lamborghini, price: 632,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/lamborghini/lurus2023green/1.webp',
                        '/images/lamborghini/lurus2023green/2.webp',
                        '/images/lamborghini/lurus2023green/3.webp',          
                        '/images/lamborghini/lurus2023green/4.webp',
                        '/images/lamborghini/lurus2023green/5.webp',          
                        '/images/lamborghini/lurus2023green/6.webp',
            ], 
        },
        {name: 'Lamborghini Aventador SVJ 2022 (YELLOW)', 
                BabyCategory: lamborghini, price: 5899,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/lamborghini/aventadorsvj2022/1.jpeg',
                        '/images/lamborghini/aventadorsvj2022/2.webp',
                        '/images/lamborghini/aventadorsvj2022/3.webp',          
                        '/images/lamborghini/aventadorsvj2022/4.jpeg',
                        '/images/lamborghini/aventadorsvj2022/5.webp',          
                        '/images/lamborghini/aventadorsvj2022/6.jpeg',
                        '/images/lamborghini/aventadorsvj2022/7.webp',
            ], 
        },
        {name: 'Lamborghini Aventador SVJ ( White )', 
                BabyCategory: lamborghini, price: 5899,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/lamborghini/aventadorsvjwhite/1.webp',
                        '/images/lamborghini/aventadorsvjwhite/2.webp',
                        '/images/lamborghini/aventadorsvjwhite/3.webp',          
                        '/images/lamborghini/aventadorsvjwhite/4.webp',
            ], 
        },
        {name: 'LAMBORGHINI HURACAN EVO 2023 (GREY)', 
                BabyCategory: lamborghini, price: 1999,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/lamborghini/huracanevo2023goldrims/1.webp',
                        '/images/lamborghini/huracanevo2023goldrims/2.webp',
                        '/images/lamborghini/huracanevo2023goldrims/3.webp',          
                        '/images/lamborghini/huracanevo2023goldrims/4.webp',
            ], 
        },
        {name: 'LAMBORGHINI HURACAN EVO 2023 (WHITE)', 
                BabyCategory: lamborghini, price: 632,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/lamborghini/huracanevo2023white/1.webp',
                        '/images/lamborghini/huracanevo2023white/2.webp',
                        '/images/lamborghini/huracanevo2023white/3.webp',          
                        '/images/lamborghini/huracanevo2023white/4.webp',
                        '/images/lamborghini/huracanevo2023white/5.webp',          
            ], 
        },
        {name: 'LAMBORGHINI HURACAN EVO SPYDER ( GREEN )', 
                BabyCategory: lamborghini, price: 2499,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/lamborghini/huracanevospydergreen/1.webp',
                        '/images/lamborghini/huracanevospydergreen/2.webp',
                        '/images/lamborghini/huracanevospydergreen/3.webp',          
                        '/images/lamborghini/huracanevospydergreen/4.webp',
                        '/images/lamborghini/huracanevospydergreen/5.webp',          
                        '/images/lamborghini/huracanevospydergreen/6.webp',
                        '/images/lamborghini/huracanevospydergreen/7.webp',
                        '/images/lamborghini/huracanevospydergreen/8.webp',
                        '/images/lamborghini/huracanevospydergreen/9.webp',
                        '/images/lamborghini/huracanevospydergreen/10.webp',
            ], 
        },
        {name: 'LAMBORGHINI HURACAN EVO SPYDER ( YELLOW )', 
                BabyCategory: lamborghini, price: 2499,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/lamborghini/huracanevospyderyellow/1.webp',
                        '/images/lamborghini/huracanevospyderyellow/2.webp',
                        '/images/lamborghini/huracanevospyderyellow/3.webp',          
                        '/images/lamborghini/huracanevospyderyellow/4.webp',
                        '/images/lamborghini/huracanevospyderyellow/5.webp',          
            ], 
        },
        {name: 'Lamborghini huracan performante spyder ( Blue )', 
                BabyCategory: lamborghini, price: 632,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/lamborghini/huracanperformantespyder/1.webp',
                        '/images/lamborghini/huracanperformantespyder/2.webp',
                        '/images/lamborghini/huracanperformantespyder/3.webp',          
                        '/images/lamborghini/huracanperformantespyder/4.webp',
                        '/images/lamborghini/huracanperformantespyder/5.webp',          
                        '/images/lamborghini/huracanperformantespyder/6.webp',
            ], 
        },
        {name: 'Lamborghini Huracan Spyder ( Black )', 
                BabyCategory: lamborghini, price: 2499,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/lamborghini/huracanspyderblack/1.webp',
                        '/images/lamborghini/huracanspyderblack/2.webp',
                        '/images/lamborghini/huracanspyderblack/3.webp',          
                        '/images/lamborghini/huracanspyderblack/4.webp',
            ], 
        },
        {name: 'Lamborghini Huracan Spyder Evo ( Green )', 
                BabyCategory: lamborghini, price: 2999,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/lamborghini/huracanspyderevogreen/1.webp',
                        '/images/lamborghini/huracanspyderevogreen/2.webp',
                        '/images/lamborghini/huracanspyderevogreen/3.webp',          
                        '/images/lamborghini/huracanspyderevogreen/4.webp',
                        '/images/lamborghini/huracanspyderevogreen/5.webp',          
                        '/images/lamborghini/huracanspyderevogreen/6.webp',
            ], 
        },
        {name: 'Lamborghini Huracan Spyder Evo ( Orange )', 
                BabyCategory: lamborghini, price: 2999,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/lamborghini/huracanspyderevoorange/1.webp',
                        '/images/lamborghini/huracanspyderevoorange/2.webp',
                        '/images/lamborghini/huracanspyderevoorange/3.webp',          
            ], 
        },
        {name: 'Lamborghini Huracan STO', 
                BabyCategory: lamborghini, price: 4599,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/lamborghini/huracansto/1.webp',
                        '/images/lamborghini/huracansto/2.webp',
                        '/images/lamborghini/huracansto/3.webp',          
                        '/images/lamborghini/huracansto/4.webp',
                        '/images/lamborghini/huracansto/5.webp',          
                        '/images/lamborghini/huracansto/6.webp',
                        '/images/lamborghini/huracansto/7.webp',
            ], 
        },
        {name: 'LAMBORGHINI HURACAN EVO 2023 (RED)', 
                BabyCategory: lamborghini, price: 2449,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/lamborghini/lambhurucanevo2023red/1.webp',
                        '/images/lamborghini/lambhurucanevo2023red/2.webp',
                        '/images/lamborghini/lambhurucanevo2023red/3.webp',          
                        '/images/lamborghini/lambhurucanevo2023red/4.webp',
                        '/images/lamborghini/lambhurucanevo2023red/5.webp',          
            ], 
        },
        {name: 'LAMBORGHINI URUS 2023 (BLUE)', 
                BabyCategory: lamborghini, price: 2449,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/lamborghini/urus2023blue/1.webp',
                        '/images/lamborghini/urus2023blue/2.webp',
                        '/images/lamborghini/urus2023blue/3.webp',          
                        '/images/lamborghini/urus2023blue/4.webp',
            ], 
        },
        {name: 'LAMBORGHINI HURACAN EVO SPYDER ( YELLOW )', 
                BabyCategory: lamborghini, price: 2499,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/lamborghini/urus2023yellow/1.webp',
                        '/images/lamborghini/urus2023yellow/2.webp',
                        '/images/lamborghini/urus2023yellow/3.webp',          
                        '/images/lamborghini/urus2023yellow/4.webp',
                        '/images/lamborghini/urus2023yellow/5.webp',          
                        '/images/lamborghini/urus2023yellow/6.webp',
            ], 
        },
        // Mercedes /////////////////
        {name: 'MERCEDES S CLASS 2021 (BLACK)', 
                BabyCategory: mercedes, price: 387,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/mercedes/sclass2021black/1.jpeg',
                        '/images/mercedes/sclass2021black/2.webp',
                        '/images/mercedes/sclass2021black/3.webp',          
                        '/images/mercedes/sclass2021black/4.webp',
                        '/images/mercedes/sclass2021black/5.webp',          
                        '/images/mercedes/sclass2021black/6.webp',
                        '/images/mercedes/sclass2021black/7.webp',
                        '/images/mercedes/sclass2021black/8.webp',
                        '/images/mercedes/sclass2021black/9.webp',
                        '/images/mercedes/sclass2021black/10.webp',
            ], 
        },
        {name: 'MERCEDES G63 AMG 2023 (BLACK)', 
                BabyCategory: mercedes, price: 412,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/mercedes/g63amg2023black/1.webp',
                        '/images/mercedes/g63amg2023black/2.webp',
                        '/images/mercedes/g63amg2023black/3.webp',          
                        '/images/mercedes/g63amg2023black/4.webp',
                        '/images/mercedes/g63amg2023black/5.webp',          
                        '/images/mercedes/g63amg2023black/6.webp',
                        '/images/mercedes/g63amg2023black/7.webp',
                        '/images/mercedes/g63amg2023black/8.webp',
                        '/images/mercedes/g63amg2023black/9.webp',
                        '/images/mercedes/g63amg2023black/10.webp',
                        '/images/mercedes/g63amg2023black/11.webp',
                        '/images/mercedes/g63amg2023black/12.webp',
            ], 
        },
        {name: 'Mercedes C200 Convertible ( White )', 
                BabyCategory: mercedes, price: 129,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/mercedes/c200convertiblewhite/1.webp',
                        '/images/mercedes/c200convertiblewhite/2.webp',
                        '/images/mercedes/c200convertiblewhite/3.webp',          
                        '/images/mercedes/c200convertiblewhite/4.webp',
            ], 
        },
        {name: 'Mercedes AMG GT 63 (BLEU)', 
                BabyCategory: mercedes, price: 335,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/mercedes/amggt63bleu/1.jpg',
            ], 
        },
        {name: 'Mercedes AMG GLE 63 (GREY NARDO)', 
                BabyCategory: mercedes, price: 999,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/mercedes/amggle63greynardo/1.webp',
                        '/images/mercedes/amggle63greynardo/2.jpg',
                        '/images/mercedes/amggle63greynardo/3.webp',
                        '/images/mercedes/amggle63greynardo/4.webp',
                        '/images/mercedes/amggle63greynardo/5.webp',
                        '/images/mercedes/amggle63greynardo/6.webp',
                        '/images/mercedes/amggle63greynardo/7.webp',
                        '/images/mercedes/amggle63greynardo/8.webp',
                        '/images/mercedes/amggle63greynardo/9.webp',
                        '/images/mercedes/amggle63greynardo/10.webp',
            ], 
        },
        {name: 'Mercedes Benz E400 Convertible', 
                BabyCategory: mercedes, price: 599,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/mercedes/benze400convertible/1.webp',
                        '/images/mercedes/benze400convertible/2.webp',
                        '/images/mercedes/benze400convertible/3.webp',
                        '/images/mercedes/benze400convertible/4.webp',
                        '/images/mercedes/benze400convertible/5.webp',
            ], 
        },
        {name: 'Mercedes C43 Convertible Black', 
                BabyCategory: mercedes, price: 599,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/mercedes/c43convertibleblack/1.webp',
                        '/images/mercedes/c43convertibleblack/2.webp',
                        '/images/mercedes/c43convertibleblack/3.webp',
                        '/images/mercedes/c43convertibleblack/4.webp',
            ], 
        },
        {name: 'Mercedes C200 2023 (WHITE)', 
                BabyCategory: mercedes, price: 799,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/mercedes/c2002023white/1.webp',
                        '/images/mercedes/c2002023white/2.webp',
                        '/images/mercedes/c2002023white/3.webp',
                        '/images/mercedes/c2002023white/4.webp',
                        '/images/mercedes/c2002023white/5.avif.avif',
            ], 
        },
        {name: 'Mercedes CLA 2021 (WHITE)', 
                BabyCategory: mercedes, price: 499,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/mercedes/cla2021/1.jpeg',
                        '/images/mercedes/cla2021/2.webp',
            ], 
        },
        {name: 'Mercedes CLA 2021 AMG (BLEU)', 
                BabyCategory: mercedes, price: 499,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/mercedes/cla2021amgblue/1.webp',
                        '/images/mercedes/cla2021amgblue/2.webp',
                        '/images/mercedes/cla2021amgblue/3.webp',
                        '/images/mercedes/cla2021amgblue/4.webp',
                        '/images/mercedes/cla2021amgblue/5.webp',
            ], 
        },
        {name: 'Mercedes E450 Convertible Black', 
                BabyCategory: mercedes, price: 499,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/mercedes/e450convertibleblack/1.webp',
                        '/images/mercedes/e450convertibleblack/2.webp',
                        '/images/mercedes/e450convertibleblack/3.webp',
                        '/images/mercedes/e450convertibleblack/4.webp',
                        '/images/mercedes/e450convertibleblack/5.webp',
                        '/images/mercedes/e450convertibleblack/6.webp',
            ], 
        },
        {name: 'Mercedes E450 Convertible Red', 
                BabyCategory: mercedes, price: 699,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/mercedes/e450convertiblered/1.webp',
                        '/images/mercedes/e450convertiblered/2.webp',
                        '/images/mercedes/e450convertiblered/3.webp',
                        '/images/mercedes/e450convertiblered/4.webp',
            ], 
        },
        {name: 'MERCEDES G63 AMG 2023 (WHITE)', 
                BabyCategory: mercedes, price: 1499,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/mercedes/g63white/1.webp',
                        '/images/mercedes/g63white/2.webp',
                        '/images/mercedes/g63white/3.webp',
                        '/images/mercedes/g63white/4.webp',
                        '/images/mercedes/g63white/5.webp',
                        '/images/mercedes/g63white/6.webp',
                        '/images/mercedes/g63white/7.webp',
                        '/images/mercedes/g63white/8.webp',
                        '/images/mercedes/g63white/9.webp',
            ], 
        },
        {name: 'Mercedes GLC200 (BLACK)', 
                BabyCategory: mercedes, price: 499,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/mercedes/glc200black/1.webp',
                        '/images/mercedes/glc200black/2.webp',
                        '/images/mercedes/glc200black/3.webp',
                        '/images/mercedes/glc200black/4.webp',
            ], 
        },
        {name: 'Mercedes GLE53 AMG ( White )', 
                BabyCategory: mercedes, price: 1199,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/mercedes/gle53amg/1.webp',
                        '/images/mercedes/gle53amg/2.webp',
                        '/images/mercedes/gle53amg/3.webp',
                        '/images/mercedes/gle53amg/4.webp',
            ], 
        },
        {name: 'Mercedes GLS 600 Maybach ( Black )', 
                BabyCategory: mercedes, price: 1199,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/mercedes/gls600maybackblack/1.webp',
                        '/images/mercedes/gls600maybackblack/2.webp',
                        '/images/mercedes/gls600maybackblack/3.webp',
                        '/images/mercedes/gls600maybackblack/4.webp',
            ], 
        },
        {name: 'Mercedes S500 Convertible ( Black )', 
                BabyCategory: mercedes, price: 1099,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/mercedes/s500convertibleblack/1.webp',
                        '/images/mercedes/s500convertibleblack/2.webp',
                        '/images/mercedes/s500convertibleblack/3.webp',
                        '/images/mercedes/s500convertibleblack/4.webp',
            ], 
        },
        {name: 'Mercedes S500 Convertible ( White )', 
                BabyCategory: mercedes, price: 1099,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/mercedes/s500convertiblewhite/1.webp',
                        '/images/mercedes/s500convertiblewhite/2.webp',
                        '/images/mercedes/s500convertiblewhite/3.webp',
                        '/images/mercedes/s500convertiblewhite/4.webp',
                        '/images/mercedes/s500convertiblewhite/5.webp',
            ], 
        },
        {name: 'MERCEDES S CLASS 2021 (WHITE)', 
                BabyCategory: mercedes, price: 1499,
                size: ['Newborn', '0-3 months', '3-6 months'],
                image:[ '/images/mercedes/sclass2021white/1.webp',
                        '/images/mercedes/sclass2021white/2.webp',
                        '/images/mercedes/sclass2021white/3.webp',
                        '/images/mercedes/sclass2021white/4.webp',
                        '/images/mercedes/sclass2021white/5.webp',
                        '/images/mercedes/sclass2021white/6.webp',
                        '/images/mercedes/sclass2021white/7.webp',
                        '/images/mercedes/sclass2021white/8.webp',
            ], 
        },
    ])
    console.log(BabyProducts)
    // console.log(BabyCategorys)
    process.exit();
})();